#!/bin/bash
# localhost-u 127.0.0.2 edin və facebook.com-u 8.8.8.8-ə yönləndirin

# 127.0.0.1 olan sətri 127.0.0.2 localhost kimi dəyişir
sed -i 's/127\.0\.0\.1/127.0.0.2/g' /etc/hosts

# Əgər facebook.com artıq yoxdursa, əlavə edir
grep -q "facebook.com" /etc/hosts || echo "8.8.8.8 facebook.com" >> /etc/hosts