#!/usr/bin/env bash
# This script configures localhost to 127.0.0.2 and redirects facebook.com to 8.8.8.8 in /etc/hosts

sed -i 's/127\.0\.0\.1/127.0.0.2/g' /etc/hosts
grep -q "facebook.com" /etc/hosts || echo "8.8.8.8 facebook.com" >> /etc/hosts